version: "2"

services:
  drupal:
    image: drupal:8.8.2
    ports:
      - 8080:80
    volumes:
      - drupal-sites:/var/www/html/sites
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
    networks:
      - drupal-network
  db:
    image: postgres:12.1
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=helloworld
    networks:
      - drupal-network
networks:
  drupal-network:
volumes:
  drupal-sites:
    external: true
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  postgres_db:
    external: true
